# 1. URL de Conexão (Montada com o host e a porta do teu print)
spring.datasource.url=jdbc:postgresql://db.cfsbnqiuhherhfzwogma.supabase.co:5432/postgres?sslmode=require

# 2. Usuário padrão do Supabase
spring.datasource.username=postgres

# 3. Senha (Apaga o texto abaixo e digita a senha que escolheste lá no início!)
spring.datasource.password=Ricley2907#

# 4. Dialeto do banco para o Hibernate conversar com o Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Mágica do Hibernate: Cria as tabelas automaticamente na nuvem ao iniciar o projeto
spring.jpa.hibernate.ddl-auto=update

# 6. Mostra os comandos SQL no console do IntelliJ para acompanhar o processo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=sua-chave-secreta-muito-longa-aqui-minimo-256-bits
jwt.expiration=86400000